### ISSUE TITLE
collapse row on move block and add block

### ISSUE THREAD

**Issue by WanjikuMac** [sFractal-Podii/quizquadaminos#141]
Once a block is moved or added - adjust the game accordingly. Eg remove a row (adding points) if the row is now complete.

**Comment by TraceyOnim** [comment]
f I understand correctly, a full row won’t clear until the next block reaches the bottom. I think this is better. It makes for some neat strategy since the score goes up exponentially with the number of rows completed (1 row=200, 2 rows=400, 3 rows =800, 4 rows =1600). So you can do several add/deletes/moves in before a block touches and completes more than one row for more points in total
