### ISSUE TITLE
Bug with "skip this question"

### ISSUE THREAD

**Issue by sparrell** [sFractal-Podii/quizquadaminos#432]
skip this question seems to work ok on bonus but it breaks the other categories. The category disappears even though there are still questions.

At this moment (may be different by time you read) there is a test server running v0.8.1 at http://peano.quadblockquiz.sfractal.com:4000
Note that authentication is not set up correctly so run anonymously.

In automation there are 10 questions (9 plus the 10th is the one it loops on in the old game). But if you skip thru them, the automation category disappears after 4 or 5. Openchain has 6 q but disappears after 3. Etc. Note I do not currently use linear numbering. eg Openchain is 1,2,3,99,101,200. Do I need to renumber them all sequentially?

**Comment by sparrell** [comment]
I suspect the problem is with qna.ex lines 33-38. Doesn't remove_unused_categories need two inputs - categories and some parameter on how many questions already answered? Where does v come from in line 35?

**Comment by TraceyOnim** [comment]
@sparrell  I have fixed the bug , the problem was that each time a question was skipped  that qna was marked as answered so that the next time the same category was selected it takes you to the next question .Since we we are marking a question when choosing a category and when skipping  a question it resulted to double marking .Instead of the next qna been 002.md it displays  003.md
